import {
	Document,
	Font,
	Image,
	Page,
	PDFDownloadLink,
	PDFViewer,
	Text,
	View,
	StyleSheet,
} from "@react-pdf/renderer";
import { Button } from "antd";
import ApprovalRecordSection from "./ApprovalRecordSection";
import ProjectDetailSection from "./ProjectDetailSection";
import ReactPdfAntdIcon from "./ReactPdfAntdIcon";
import { MailOutlined } from "@ant-design/icons";
import ApproveTimeSection from "./ApproveTimeSection";

// Register font
const font_source = "/src/assets/fonts/aeonikPro.woff";
Font.register({
	family: "AeonikPro",
	src: font_source,
});

export const styles = StyleSheet.create({
	body: {
		fontFamily: "AeonikPro",
		paddingTop: 35,
		paddingBottom: 65,
		paddingHorizontal: 20,
	},
	header: {
		fontSize: 14,
		fontWeight: "bold",
		textAlign: "center",
		marginBottom: 20,
	},
	footer: {
		position: "absolute",
		bottom: 30,
		right: 20,
		fontSize: 10,
	},
	section: {
		marginBottom: 20,
	},
	email: {
		fontSize: 8,
		textAlign: "right",
		color: "#A8A8A8",
	},
	tableHeader: {
		fontSize: 12,
		fontWeight: "bold",
		padding: 8,
		backgroundColor: "#00003C",
		color: "#fff",
		width: "100%",
		border: "1px solid #00003C",
	},
	tableBody: {
		fontSize: 10,
		padding: 8,
	},
	// cell: {
	//     border: "1px solid #A8A8A8",
	// },
	border: {
		border: "1px solid #A8A8A8",
	},
	flexRow: {
		display: "flex",
		flexDirection: "row",
	},
	flexColumn: {
		display: "flex",
		flexDirection: "column",
	},
	row: {
		display: "flex",
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
		width: "100%",
		padding: 8,
		backgroundColor: "#f0f0f0",
	},
	qrContainer: {
		display: "flex",
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
	},
	qrImage: {
		width: 50,
		height: 50,
	},
	width20percent: {
		width: "20%",
	},
});

const MyDocument = () => (
	<Document>
		<Page size="A3" style={styles.body}>
			<View fixed>
				<Text style={styles.header}>Timewriting</Text>
				<View
					style={[
						// styles.flexColumn,
						{
							position: "absolute",
							right: 0,
							top: 0,
							textAlign: "right",
							justifyContent: "flex-end",
							// fontSize: 14,
						},
					]}
				>
					<Image
						style={[{ width: 50, border: "1px solid #000" }]}
						src={"/src/assets/images/logo.png"}
					/>
					<Text style={styles.email}>
						accountspayables@elementalenergies.com
					</Text>
				</View>
			</View>

			<ProjectDetailSection />
			<ApproveTimeSection month={"2025-02"} />
			<ApprovalRecordSection />

			<Text style={[styles.footer]} fixed>
				Report Generated by John Doe on 08 Mar 2025 17:30:21 UTC
			</Text>
		</Page>
	</Document>
);

function PdfViewer() {
	return (
		<div
			style={{
				display: "flex",
				flexDirection: "column",
				alignItems: "center",
				justifyContent: "center",
				height: "100vh",
				gap: "20px",
			}}
		>
			<h1>PDF Viewer</h1>

			{/* PDF View */}
			<PDFViewer width="1000" height="600">
				<MyDocument />
			</PDFViewer>

			{/* Download PDF */}
			<PDFDownloadLink document={<MyDocument />} fileName="example.pdf">
				{({ loading }) => (
					<Button loading={loading} type="primary">
						Download PDF
					</Button>
				)}
			</PDFDownloadLink>
		</div>
	);
}

export default PdfViewer;
